#!/bin/bash
# Copyright © 2017-2018 Nonna Holding AB
# Distributed under the MIT license, see license text in LICENSE.Malterlib

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASH_SOURCE_FULL="$DIR/${BASH_SOURCE[0]##*/}"

set -e

cd "$DIR"

if [ -e .malterlib_only_repos ] && [[ "$MalterlibOnlyRepositoryManagement" == "" ]]; then
	export MalterlibOnlyRepositoryManagement=true
fi

if [ -e Binaries/Malterlib/LICENSE.Malterlib ]; then
	rm -rf Binaries/Malterlib
fi

if [ -e Malterlib/Core ]; then
	find "$DIR/Malterlib/Core" -maxdepth 0 -type d -empty -exec rmdir {} \;
fi

function OutputInfo()
{
	if [[ "$TERM" == "dumb" ]]; then
		echo $'\e[1m\e[36m'"$@"$'\e[0m'
	else
		echo $'\e[38;5;39m'"$@"$'\e[0m'
	fi
}

function OutputNote()
{
	if [[ "$TERM" == "dumb" ]]; then
		echo $'\e[1m\e[33m'"$@"$'\e[0m'
	else
		echo $'\e[38;5;221m'"$@"$'\e[0m'
	fi
}

function OutputHeading()
{
	if [[ "$TERM" == "dumb" ]]; then
		echo $'\e[1m\e[32m'"$@"$'\e[0m'
	else
		echo $'\e[38;5;118m'"$@"$'\e[0m'
	fi
}

function OutputError()
{
	if [[ "$TERM" == "dumb" ]]; then
		echo $'\e[1m\e[31m'"$@"$'\e[0m'
	else
		echo $'\e[38;5;198m'"$@"$'\e[0m'
	fi
}

BootstrapInit=false
function BootstrapInit()
{
	if $BootstrapInit; then
		return
	fi

	BootstrapInit=true

	echo
	OutputHeading '/¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\'
	OutputHeading '| Bootstrapping Malterlib |'
	OutputHeading '\_________________________/'
	echo

	# Make sure that lfs is installed
	if ! git lfs > /dev/null ; then
		echo Please install git lfs
		exit 1
	fi

	if ! cat ~/.gitconfig | grep 'filter "lfs"' > /dev/null ; then
		git lfs install
	fi

	if [[ "$MalterlibPlatform" ==  Windows ]]; then
		git config --global core.symlinks true
	fi
}

function ReportBootstrapDone()
{
	if ! $BootstrapInit; then
		return
	fi

	OutputHeading '/¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\'
	OutputHeading '| Successfully bootstrapped Malterlib |'
	OutputHeading '\_____________________________________/'
	echo
}

function DetectRepoRoot()
{
	if [[ "$MalterlibRepoRoot" == "" ]]; then

		OutputInfo "Determine MalterlibRepoRoot from *.MBuildSystem:"

		MalterlibRepoRoot=https://github.com/Malterlib
		BuildSystemContents=`cat *.MBuildSystem | grep MalterlibRepoRoot || true`

		ToMatch='[ \t]*MalterlibRepoRoot[ \t]+(.*)'
		while [[ $BuildSystemContents =~ $ToMatch ]]; do
			BuildSystemContents=${BASH_REMATCH[1]}
			break
		done

		ToMatch='^"(.*)"$'
		while [[ $BuildSystemContents =~ $ToMatch ]]; do
			BuildSystemContents=${BASH_REMATCH[1]}
			break
		done
		if [[ "$BuildSystemContents" != "" ]]; then
			MalterlibRepoRoot="$BuildSystemContents"
			echo "Found customized MalterlibRepoRoot: `OutputNote "$MalterlibRepoRoot"`"
		else
			echo "Using default MalterlibRepoRoot: `OutputNote "$MalterlibRepoRoot"`"
		fi

		echo
	fi
}

function GetMalterlibCoreHash()
{
	cat *.MRepo | grep -A2 '"Malterlib/Core"' | grep '"Hash":' | cut '-d ' -f 2 | tr -d '"' || true
}

MalterlibChangingBootstrapVersion="false"
BootstrapVersion="4"
MalterlibCoreBootstrapVersion="2"

function BootstrapCore()
{
	if ! [ -e Malterlib/Core ]; then
		BootstrapInit
		DetectRepoRoot

		if ! [ -e Malterlib/Core ]; then

			OutputInfo "Cloning Malterlib/Core"

			GitHash=`GetMalterlibCoreHash`
			if [[ "$GitHash" != "" ]]; then
				echo "Found commit hash in *.MRepo files: `OutputNote "$GitHash"`"

				git clone -n "$MalterlibRepoRoot/Malterlib_Core.git" Malterlib/Core
				pushd Malterlib/Core > /dev/null
				git checkout -B master $GitHash
				popd > /dev/null
			else
				OutputError "Could not find commit hash in *.MRepo files using latest default branch"

				git clone "$MalterlibRepoRoot/Malterlib_Core.git" Malterlib/Core
			fi

			echo
		fi
	fi

	MalterlibCoreBootstrapVersion="2"

	if [ -e "Malterlib/Core/Bootstrap.version" ]; then
		MalterlibCoreBootstrapVersion=`cat "Malterlib/Core/Bootstrap.version"`
	fi

	if ! [ -e ./Malterlib/Core/Scripts/Detect.sh ] || [[ "$MalterlibCoreBootstrapVersion" != "$BootstrapVersion" ]]; then
		# Upgrade path
		export MalterlibChangingBootstrapVersion=true

		git -C Malterlib/Core fetch --all --tags

		GitHash=`GetMalterlibCoreHash`
		if [[ "$GitHash" == "" ]]; then
			OutputError "Could not find commit hash in *.MRepo, cannot upgrade"
			exit 1
		fi

		if [[ "$MalterlibRepositoryHardReset" == "true" ]] || (git -C Malterlib/Core branch -r --contains HEAD > /dev/null && [ -z "$(git -C Malterlib/Core status --porcelain || echo no)" ]); then
			git -C Malterlib/Core checkout -B master $GitHash
		else
			OutputError "Malterlib/Core is not clean, please resolve the situation before trying to upgrade"
			exit 1
		fi
	fi

	source ./Malterlib/Core/Scripts/Detect.sh
	if [[ "$MalterlibPlatform" ==  Windows ]]; then
		mkdir -p /tmp
	fi

	MalterlibBinariesPath="Binaries/Malterlib/${MalterlibPlatform}/${MalterlibArch}"
	MalterlibBinariesRepo="MalterlibBinaries_${MalterlibPlatform}_${MalterlibArch}"

	if [ -e "$MalterlibBinariesPath" ]; then
		find "$DIR/$MalterlibBinariesPath" -maxdepth 0 -type d -empty -exec rmdir {} \;
	fi

	if ! [ -e "$MalterlibBinariesPath/Bootstrap.version" ] || [[ `cat "$MalterlibBinariesPath/Bootstrap.version"` != "$BootstrapVersion" ]]; then
		echo Removing binaries because they are not compatible with current bootstrap process
		rm -rf "$MalterlibBinariesPath"
		export MalterlibChangingBootstrapVersion=true
	fi

	if [[ "$MalterlibChangingBootstrapVersion" == "true" ]]; then
		export Malterlib_UseCachedEnvironment=false
		if [ -e "BuildSystem/Default/RepositoryState.json" ]; then
			while read a; do
			    echo ${a//\"\"\: 1\,/}
			done < BuildSystem/Default/RepositoryState.json > BuildSystem/Default/RepositoryState.json.new
			mv BuildSystem/Default/RepositoryState.json{.new,}
		fi
	fi

	if ! [ -e "$MalterlibBinariesPath" ]; then
		BootstrapInit
		DetectRepoRoot

		if ! [ -e "$MalterlibBinariesPath" ]; then

			OutputInfo "Cloning $MalterlibBinariesPath"

			RepoFolder="Malterlib/Core/"
			GitHash=`cat Malterlib/Core/*.MRepo | grep -A2 "\"\\.\\./\\.\\./$MalterlibBinariesPath\"" | grep '"Hash":' | cut '-d ' -f 2 | tr -d '"' || true`

			if [[ "$GitHash" != "" ]]; then
				echo "Found commit hash in ${RepoFolder}*.MRepo files: `OutputNote "$GitHash"`"

				git clone -n "$MalterlibRepoRoot/$MalterlibBinariesRepo.git" $MalterlibBinariesPath
				pushd $MalterlibBinariesPath > /dev/null
				git checkout -B master $GitHash
				popd > /dev/null
			else
				OutputError "Could not find commit hash in ${RepoFolder}*.MRepo files using latest default branch"

				git clone "$MalterlibRepoRoot/$MalterlibBinariesRepo.git" $MalterlibBinariesPath
			fi

			echo
		fi
	fi

	ReportBootstrapDone
}

BootstrapCore

export MalterlibBinariesPath
export MalterlibScriptPath="$DIR"
export MalterlibBashSourceFull="$BASH_SOURCE_FULL"

ScriptsDir="$PWD/Malterlib/Core/Scripts"
NumArguments=$#
if (( $NumArguments >= 1 )); then
	Command=$1
	shift
fi

RetriedBootstrap="false"

while true; do

	function UpdateMTool()
	{
		if [[ "$MalterlibPlatform" ==  Windows ]] || [[ "$MalterlibSafeMib" == "true" ]]; then
			DependencyFile=BuildSystem/SafeMib/SafeMib.MalterlibDependency

			if [ -e "$DependencyFile" ]; then
				"$MToolExecutable" CheckDependencies Verbose=true "Directory=BuildSystem/SafeMib"
			fi

			if ! [ -e BuildSystem/SafeMib/SafeMib.updated ]; then
				echo Updating safe binaries

				ExcludePatterns="*/.git;*/.DS_Store;*.TMP"

				MalterlibDiffCopyExcludePatterns="$ExcludePatterns" "$MToolExecutable" DiffCopy "$MalterlibBinariesPath/*" "BuildSystem/SafeMib/Binaries" "" 1 1
				MalterlibDiffCopyExcludePatterns="$ExcludePatterns" "$MToolExecutable" DiffCopy "Malterlib/Core/Scripts/*" "BuildSystem/SafeMib/Scripts" "" 1 1
				"$MToolExecutable" TouchOrCreate "BuildSystem/SafeMib/SafeMib.updated"

				if type MalterlibConvertPath > /dev/null; then
					"$MToolExecutable" BuildDependencies "OutputFile=`MalterlibConvertPath \"$MalterlibScriptPath/$DependencyFile\"`" \
					"Output:`MalterlibConvertPath \"$MalterlibScriptPath/BuildSystem/SafeMib/SafeMib.updated\"`" \
					"Input:`MalterlibConvertPath \"$MalterlibBashSourceFull\"`" \
					"Find:`MalterlibConvertPath \"$MalterlibBinariesPath\"`/*;RIF;33;$ExcludePatterns" \
					"Find:`MalterlibConvertPath \"$MalterlibScriptPath/Malterlib/Core/Scripts\"`/*;RIF;33;$ExcludePatterns"
				else
					rm -f BuildSystem/SafeMib/SafeMib.updated
				fi
			fi

			export MalterlibBinariesDir="$PWD/BuildSystem/SafeMib/Binaries"
			ScriptsDir="$PWD/BuildSystem/SafeMib/Scripts"
		fi
	}

	UpdateMTool

	export -f UpdateMTool

	function RunTests()
	{
		Start=$SECONDS

		function OutputTime()
		{
			OutputNote "$((SECONDS-Start)) s"
			Start=$SECONDS
			echo
		}

		OutputInfo '[Generating]'
		./mib generate Tests
		source BuildSystem/SharedBuildSettings.sh
		export MalterlibXCPrettyOptions="-t"
		OutputTime

		OutputInfo '[Building]'
		./mib build Tests "$HostPlatform" "$HostArchitecture" "$1"
		OutputTime

		OutputInfo '[Testing]'

		if "$MalterlibDeployRoot/Tests/RunAllTests" --quiet ; then
			OutputTime
			OutputHeading Success
		else
			OutputTime
			OutputError "Tests FAILED"
			exit 1
		fi
	}

	case "$Command" in
		generate)
			MissingSetup=false
			if [[ "$MalterlibPlatform" == macOS ]] ; then
				if [ -e ./Malterlib/Core/Setup/macOS/setup.sh ]; then
					./Malterlib/Core/Setup/macOS/setup.sh CheckSetup
				else
					MissingSetup=true
				fi
			fi

			set +e

			"$ScriptsDir/mib.sh" generate "$@"

			MToolExit=$?
			set -e

			if [[ "$MalterlibChangingBootstrapVersion" == "true" ]] && [[ "$RetriedBootstrap" == "false" ]]; then
				if [[ $MToolExit > 0 ]]; then
					RetriedBootstrap="true"
					echo MTool potentially updated, running bootstrap again
					BootstrapCore
					continue
				fi
			fi

			if [[ $MToolExit != 2 ]]; then
				exit $MToolExit
			fi

			if $MissingSetup && [[ "$MalterlibPlatform" == macOS ]] && [ -e ./Malterlib/Core/Setup/macOS/setup.sh ]; then
				./Malterlib/Core/Setup/macOS/setup.sh CheckSetup
			fi
		;;
		setup_only)
			# TODO: deprecate this
			exit 0
		;;
		bootstrap_only)
			exit 0
		;;
		setup)
			if [[ "$MalterlibPlatform" == macOS ]] ; then
				./Malterlib/Core/Setup/macOS/setup.sh "$@"
			fi
		;;
		build)
			./Malterlib/Core/BuildScripts/BuildWorkspace.sh "$@"
		;;
		test)
			Config=Debug
			if [[ "$1" != "" ]]; then
				Config="$1"
			fi
			RunTests "$Config"
		;;
		test_release)
			RunTests "Release (Tests)"
		;;
		build_target)
			./Malterlib/Core/BuildScripts/BuildTarget.sh "$@"
		;;
		prebuild)
			./Malterlib/Core/BuildScripts/Prebuild.sh "$@"
		;;
		postbuild)
			./Malterlib/Core/BuildScripts/Postbuild.sh "$@"
		;;
		detect_system)
			source ./Malterlib/Core/BuildScripts/DetectSystem.sh "$@"
		;;
		*)
			set +e
			if (( $NumArguments >= 1 )); then
				"$ScriptsDir/mib.sh" "$Command" "$@"
			else
				"$ScriptsDir/mib.sh" "$@"
			fi
			MToolExit=$?
			set -e

			if [[ "$MalterlibChangingBootstrapVersion" == "true" ]] && [[ "$RetriedBootstrap" == "false" ]]; then
				if [[ $MToolExit > 0 ]]; then
					RetriedBootstrap="true"
					echo MTool potentially updated, running bootstrap again
					BootstrapCore
					continue
				fi
			fi

			exit $MToolExit
	esac

	break

done
